//list of icmpType for V6
//gather from Firewall => add new rule v4 => IPv4 ICMP Type Name

export type icmpTypeV4 =
    | ''
    | 'communication-prohibited'
    | 'destination-unreachable'
    | 'echo-reply'
    | 'echo-request'
    | 'fragmentation-needed'
    | 'host-precedence-violation'
    | 'host-prohibited'
    | 'host-redirect'
    | 'host-unknown'
    | 'host-unreachable'
    | 'ip-header-bad'
    | 'network-prohibited'
    | 'network-redirect'
    | 'network-unknown'
    | 'network-unreachable'
    | 'parameter-problem'
    | 'port-unreachable'
    | 'protocol-unreachable'
    | 'redirect'
    | 'required-option-missing'
    | 'router-advertisement'
    | 'router-solicitation'
    | 'source-route-failed'
    | 'timestamp-reply'
    | 'timestamp-request'
    | 'TOS-host-redirect'
    | 'TOS-host-unreachable'
    | 'TOS-network-redirect'
    | 'TOS-network-unreachable'
    | 'ttl-exceeded'
    | 'ttl-zero-during-reassembly'
    | 'ttl-zero-during-transit';
