//list of protocol for V6
//gather from Firewall => add new rule v6 => IPv6 protocol

export type protocolV6 =
    | 'all'
    | 'tcp'
    | 'udp'
    | 'tcp_udp'
    | 'icmpv6'
    | 'ah'
    | 'dccp'
    | 'eigrp'
    | 'esp'
    | 'gre'
    | 'ipcomp'
    | 'ipv6'
    | 'ipv6-frag'
    | 'ipv6-icmp'
    | 'ipv6-nonxt'
    | 'ipv6-opts'
    | 'ipv6-route'
    | 'isis'
    | 'l2tp'
    | 'manet'
    | 'mobility-header'
    | 'mpls-in-ip'
    | 'ospf'
    | 'pim'
    | 'rsvp'
    | 'sctp'
    | 'shim6'
    | 'vrrp'
    | 'number'
    | string;
