name: Release
on:
  release:
    types: [created]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
        #can't test on 5.6.42 because database is too up to date ( 5.12.72 )
        unifi-version: [ latest, version-6.0.23, version-6.0.28, version-6.0.36, version-6.0.41, version-6.0.43, version-6.0.45 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: ${{ matrix.node-version }}

      - name: install+run docker-unifi-controller
        run: |
          run: |
            # install our own demo database
            mkdir unifi-storage
            sudo tar -C unifi-storage -xf $GITHUB_WORKSPACE/.github/workflows/db-demo-dump.tar.bz2
            # create docker-unifi-controller
            docker create --name=unifi-controller -e PUID=1001 -e PGID=116 -e MEM_LIMIT=1024M -p 8443:8443 -v $GITHUB_WORKSPACE/unifi-storage:/config linuxserver/unifi-controller:${{ matrix.unifi-version }}
            docker start unifi-controller
            # wait for unifi-controller to be ready
            while ! curl -ks https://127.0.0.1:8443; do echo waiting for unifi-controller; sleep 2; done
            echo unifi-controller answer

      # run npm tests
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          echo start tests
          npm run test:CI
        env:
          CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
        env:
          CI: true
      - run: npm publish --access public
        name: publish on npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


